export const privacyPolicies = {
  openfolder: {
    updated: 'November 25, 2025',
    platform: 'macOS',
    overview: `OpenFolder is a macOS menu bar utility designed to help you open your most-used files, folders, and apps in two taps. The app works entirely on your device and does not send personal data to external servers controlled by the developer. Purchases are fulfilled through Apple's App Store infrastructure.`,
    sections: [
      {
        title: 'Data We Collect',
        body: [
          'OpenFolder does not collect analytics, personal identifiers, or usage metrics for tracking purposes. All app actions occur locally on your Mac.',
          'The app does not require you to create an account and never transmits content you add to your favorites list.',
          'For subscription management, RevenueCat SDK generates an anonymous user ID that is stored locally and used to sync your subscription status across devices. This ID cannot be linked to your identity.',
          'No personally identifiable information (PII) such as name, email, IP address, or Apple ID is collected or stored by OpenFolder or RevenueCat.',
          'The only local data stored is your favorites list (file paths, folder paths, app bundle identifiers) and app preferences, all kept within the app sandbox.'
        ]
      },
      {
        title: 'How Data is Collected & Stored',
        body: [
          'When you add an item to OpenFolder, the app requests a security-scoped bookmark from macOS. This is a system-level permission that allows persistent access to files outside the sandbox.',
          'These bookmarks are stored in encrypted format using macOS UserDefaults or Core Data within the app\'s container: ~/Library/Containers/com.yourcompany.openfolder/',
          'All data storage is local-only. No data is sent to external servers, cloud services, or third-party providers (except RevenueCat for subscription management).'
        ]
      },
      {
        title: 'File & Folder Access Permissions',
        body: [
          'When you add files, folders, or apps to OpenFolder, the application asks macOS for a security-scoped bookmark so it can reopen those items later.',
          'These bookmarks are stored securely within the app\'s sandbox. They are only used to launch the items you explicitly added and are never shared with the developer or third parties.',
          'OpenFolder never accesses the contents of your files. It only stores references (paths) to open them with the default app when you click them.',
          'You can revoke access at any time by removing items from your favorites list or uninstalling the app.'
        ]
      },
      {
        title: 'Third-Party Services & SDKs',
        body: [
          'OpenFolder uses RevenueCat SDK to manage in-app purchases and subscriptions. RevenueCat acts as a wrapper around Apple\'s StoreKit and helps manage subscription status across devices.',
          'RevenueCat collects the following data: anonymous app user ID (generated by RevenueCat), subscription status, purchase events, and device/OS information. No personally identifiable information is collected.',
          'RevenueCat\'s data collection is limited to subscription management and does not include analytics, advertising, or tracking. For details, see RevenueCat\'s Privacy Policy at https://www.revenuecat.com/privacy',
          'The app uses Apple\'s native StoreKit framework for payment processing. All payment information is processed by Apple, not by OpenFolder or RevenueCat.',
          'OpenFolder does NOT use the following services: Google Analytics, Firebase, Facebook SDK, Mixpanel, Amplitude, Sentry, iCloud sync, or any advertising networks.'
        ]
      },
      {
        title: 'Network Activity',
        body: [
          'RevenueCat SDK communicates with RevenueCat servers to sync subscription status and verify purchases. This includes the anonymous user ID, subscription events, and device information.',
          'StoreKit communicates with Apple servers to process payments and verify purchase receipts. This is handled entirely by Apple and does not expose personal data to the developer.',
          'The app does not run background analytics, tracking, or advertising network requests.',
          'No telemetry, crash reporting, or usage tracking is transmitted over the network unless you explicitly opt in via macOS System Settings (see "Crash Logs & Diagnostics" below).'
        ]
      },
      {
        title: 'Crash Logs & Diagnostics',
        body: [
          'If you opt in to share analytics with developers in macOS System Settings, Apple may provide anonymized crash logs. These logs do not contain personal data and are used strictly to improve stability.',
          'You can disable this sharing at any time by navigating to System Settings → Privacy & Security → Analytics & Improvements.',
          'Crash logs may include device model, macOS version, and stack traces but never include file paths, favorites data, or personal identifiers.',
          'These logs are provided by Apple and are subject to Apple\'s privacy practices, not directly collected by OpenFolder.'
        ]
      },
      {
        title: 'Data Retention & Deletion',
        body: [
          'Local data (favorites, preferences, security-scoped bookmarks) is retained indefinitely until you delete items manually or uninstall the app.',
          'Uninstalling OpenFolder permanently deletes all local data from your Mac. This includes favorites, preferences, and cached data.',
          'RevenueCat retains the anonymous user ID and subscription history on their servers for subscription management purposes. This data is retained according to RevenueCat\'s data retention policy (typically for the duration of your subscription plus a reasonable period for support).',
          'You can request deletion of your RevenueCat data by contacting support at fzero17@qq.com. We will submit a deletion request to RevenueCat on your behalf.',
          'Support emails and correspondence are retained for 90 days after resolution, then permanently deleted unless legal obligations require longer retention.',
          'No data is retained on external servers operated by the developer. Subscription data is managed by RevenueCat as described above.'
        ]
      },
      {
        title: 'Subscription & Purchase Data',
        body: [
          'OpenFolder does not store your payment information. All transactions are processed by Apple through StoreKit.',
          'RevenueCat stores an anonymous user ID and subscription status on its servers to enable cross-device subscription syncing. This data cannot identify you personally.',
          'Your purchase history is managed by Apple and visible in your App Store account. OpenFolder and RevenueCat only check whether you have an active subscription.',
          'If you cancel or uninstall, the anonymous RevenueCat ID and subscription status remain on RevenueCat servers according to their retention policy. Apple retains purchase records according to their policies.',
          'You can request deletion of your RevenueCat data by contacting support at fzero17@qq.com.'
        ]
      },
      {
        title: 'Your Rights & Choices',
        body: [
          'Access: All data is stored locally and accessible to you at any time through the app interface.',
          'Deletion: You can delete individual items from your favorites list or uninstall the app to remove all data.',
          'Portability: Your favorites list can be exported (if the app supports it) or manually recreated since it\'s just a list of file paths.',
          'Opt-out: You can disable analytics sharing and crash reporting at any time through macOS System Settings.',
          'If you are in the EU, you have additional rights under GDPR. Since no personal data is collected or transmitted, most GDPR provisions do not apply, but you can contact support with any concerns.'
        ]
      },
      {
        title: 'Support & Contact',
        body: [
          'If you contact support via email, any information you provide (such as logs or screenshots) is used solely to address your request and is deleted once assistance is complete unless further retention is required by law.',
          'Reach out at fzero17@qq.com for privacy questions or support needs.',
          'When contacting support, only provide information necessary to resolve your issue. Never send passwords, credit card numbers, or other sensitive data.',
          'Support emails are stored securely and accessed only by authorized personnel.'
        ]
      },
      {
        title: 'Children\'s Privacy',
        body: [
          'OpenFolder is not directed at children under 13 (or applicable age in your jurisdiction).',
          'We do not knowingly collect data from children. If you believe a child has used OpenFolder and data was inadvertently collected, contact us immediately.',
          'Parents can review and delete any data by accessing the app on their child\'s device.'
        ]
      },
      {
        title: 'Changes to Privacy Policy',
        body: [
          'We may update this Privacy Policy to reflect changes in the app, legal requirements, or best practices.',
          'Material changes will be communicated via the app, website, or email if you\'ve provided contact information.',
          'Continued use of OpenFolder after changes take effect constitutes acceptance of the revised policy.',
          'The most current version will always be available at our website and within the app.'
        ]
      },
      {
        title: 'Legal Compliance',
        body: [
          'OpenFolder complies with applicable data protection laws including GDPR (EU), CCPA (California), and other regional privacy regulations.',
          'We may disclose information if required by law, court order, or government request.',
          'In the event of a merger, acquisition, or sale of assets, user data (if any) would be transferred subject to this Privacy Policy.',
          'For legal inquiries, contact fzero17@qq.com with "Legal" in the subject line.'
        ]
      }
    ]
  }
};
